### ISSUE TITLE
How to attach property to Product

### ISSUE THREAD

**Issue by mucan54** [vanilophp/properties#3]
How can we use property or attach a value of property for a product

**Comment by fulopattila122** [comment]
Are you using the Vanilo Framework and its Product model or do you want to assign properties to a Product model of yours?

If you're using the framework, then it already does everything. ✅

If you want to assign property values to your own model, then add the [HasPropertyValues](https://github.com/vanilophp/properties/blob/2.1.1/src/Traits/HasPropertyValues.php) trait to your model and then do:

```php
$product->propertyValues()->sync($propertyValueIds);
```

The functionality works via standard [Eloquent Relationships](https://laravel.com/docs/8.x/eloquent-relationships#syncing-associations)

**Comment by mucan54** [comment]
I want to use my own model and I will list all properties on a form get the values from post request and update all property values of my model. So can I use fill

**Comment by fulopattila122** [comment]
Yes `fill` works as well. We're using `sync`, because it covers all the cases, when a user unclicks some or all the values.
But it's really up to you.
